### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference when running fetch command

### ISSUE THREAD

**Issue by natea** [jdevoo/nucoll#2]
When running the `fetch` command, I got this strange error:

```
2020/02/18 21:36:16 processed mcuban
2020/02/18 21:36:16 response code 429 received; waiting until 21:51:21 to resume
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x124b778]

goroutine 1 [running]:
github.com/jdevoo/nucoll/twitter.(*NucollTransport).RoundTrip(0xc00000a3a0, 0xc0005a4400, 0xc00000a3a0, 0x0, 0x0)
	/home/jdevoo/lib/go/src/github.com/jdevoo/nucoll/twitter/client.go:44 +0x218
net/http.send(0xc0005a4400, 0x132fb40, 0xc00000a3a0, 0x0, 0x0, 0x0, 0xc00000c158, 0xc000420d50, 0xc0000ad8f8, 0x1)
	/usr/local/go/src/net/http/client.go:250 +0x14b
net/http.(*Client).send(0xc00000ef60, 0xc0005a4400, 0x0, 0x0, 0x0, 0xc00000c158, 0x0, 0x1, 0x0)
	/usr/local/go/src/net/http/client.go:174 +0xfa
net/http.(*Client).do(0xc00000ef60, 0xc0005a4400, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/client.go:641 +0x2a8
net/http.(*Client).Do(0xc00000ef60, 0xc0005a4400, 0xc00017a660, 0x51, 0x0)
	/usr/local/go/src/net/http/client.go:509 +0x35
net/http.(*Client).Get(0xc00000ef60, 0xc00017a660, 0x51, 0x2, 0x2, 0xc00017a660)
	/usr/local/go/src/net/http/client.go:398 +0x9d
github.com/jdevoo/nucoll/twitter.Twitter.ids(0xc00000ef60, 0x12e5781, 0x7, 0xc0004687f0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/jdevoo/lib/go/src/github.com/jdevoo/nucoll/twitter/cmds.go:83 +0x1fb
github.com/jdevoo/nucoll/twitter.Twitter.Fetch(0xc00000ef60, 0xc00000e000, 0x1388, 0xc00000e0e0, 0x1, 0x1)
	/home/jdevoo/lib/go/src/github.com/jdevoo/nucoll/twitter/cmds.go:313 +0x43c
main.main()
	/home/jdevoo/lib/go/src/github.com/jdevoo/nucoll/cmd.go:136 +0x2e4
```

**Comment by jdevoo** [comment]
Thank you Nate - can you share what command and handle you were trying nucoll on? So I can reproduce this somehow...

**Comment by natea** [comment]
I was running `nucoll fetch natea`
is there any way to speed up the process? it's been running for days. or is that just a limitation of the Twitter API?

**Comment by jdevoo** [comment]
I took a guess and started running it on my side. With the [rate limiting](https://developer.twitter.com/en/docs/basics/rate-limiting) it is a slow process indeed. It's been running as a background task and haven't had an exception come up yet. Wonder what caused the issue above...
